# Generated by Django 2.2.2 on 2019-12-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190813_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='profile_fon',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='model_pic',
            field=models.ImageField(blank=True, default='media/friend.jpg', upload_to='media/', verbose_name='fon_image'),
        ),
    ]
